<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.82FpWAs' shared service.

return $this->privates['.service_locator.82FpWAs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'professional' => ['privates', '.errored..service_locator.82FpWAs.App\\Entity\\Professional', NULL, 'Cannot autowire service ".service_locator.82FpWAs": it references class "App\\Entity\\Professional" but no such service exists.'],
]);
