<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cjvg1bk' shared service.

return $this->privates['.service_locator.cjvg1bk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'specialty' => ['privates', '.errored..service_locator.cjvg1bk.App\\Entity\\Specialty', NULL, 'Cannot autowire service ".service_locator.cjvg1bk": it references class "App\\Entity\\Specialty" but no such service exists.'],
]);
