<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProfessionalController::delete' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\ProfessionalController::edit' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\ProfessionalController::index' => ['privates', '.service_locator.EfjjASI', 'get_ServiceLocator_EfjjASIService.php', true],
    'App\\Controller\\ProfessionalController::show' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\SpecialtyController::delete' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
    'App\\Controller\\SpecialtyController::edit' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
    'App\\Controller\\SpecialtyController::index' => ['privates', '.service_locator.GNsOZN1', 'get_ServiceLocator_GNsOZN1Service.php', true],
    'App\\Controller\\SpecialtyController::show' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
    'App\\Controller\\ProfessionalController:delete' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\ProfessionalController:edit' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\ProfessionalController:index' => ['privates', '.service_locator.EfjjASI', 'get_ServiceLocator_EfjjASIService.php', true],
    'App\\Controller\\ProfessionalController:show' => ['privates', '.service_locator.82FpWAs', 'get_ServiceLocator_82FpWAsService.php', true],
    'App\\Controller\\SpecialtyController:delete' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
    'App\\Controller\\SpecialtyController:edit' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
    'App\\Controller\\SpecialtyController:index' => ['privates', '.service_locator.GNsOZN1', 'get_ServiceLocator_GNsOZN1Service.php', true],
    'App\\Controller\\SpecialtyController:show' => ['privates', '.service_locator.cjvg1bk', 'get_ServiceLocator_Cjvg1bkService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
